openapi: 3.0.3
info:
  title: Teachable Checkout API
  version: 1.0.0
  description: API for creating and tracking Stripe Checkout Sessions. Hosted mode is used by default. Embedded mode is also supported for testing.

servers:
  - url: https://staging.teachable.com/api
    description: Staging environment using Stripe Staging API Keys.

paths:
  /checkout/session:
    post:
      summary: Create a Checkout Session
      description: >
        Creates a Stripe Checkout Session.

        Hosted mode (default) requires success_url and cancel_url.

        Embedded mode (ui_mode=embedded) does not allow success_url or cancel_url.
        For embedded sessions, redirect_on_completion is set to "never".
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                amount:
                  type: integer
                  description: Amount in cents. Defaults to 1000 ($10).
                  example: 1000
                currency:
                  type: string
                  description: ISO currency code. Defaults to "usd".
                  example: usd
                product_name:
                  type: string
                  description: Name of the product. Defaults to "Test Product".
                  example: Test Product
                success_url:
                  type: string
                  description: Required for hosted mode only. URL for redirect after payment success.
                  example: https://example.org/success
                cancel_url:
                  type: string
                  description: Required for hosted mode only. URL for redirect if payment is cancelled.
                  example: https://example.org/cancel
                mode:
                  type: string
                  enum: [payment, subscription]
                  default: payment
                  description: Payment or subscription mode.
                customer_email:
                  type: string
                  description: Optional email for pre-filling checkout. Must be valid if provided.
                  example: test@example.com
                ui_mode:
                  type: string
                  enum: [hosted, embedded]
                  default: hosted
                  description: >
                    Controls the Checkout UI mode. "hosted" uses Stripe-hosted pages.
                    "embedded" uses embedded checkout with no redirects.
      responses:
        '201':
          description: Checkout Session created.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    example: cs_test_12345
                  url:
                    type: string
                    example: https://checkout.stripe.com/pay/cs_test_12345

  /checkout/session/{session_id}:
    get:
      summary: Retrieve a Checkout Session
      description: >
        Fetches details and status of a Checkout Session.
        Possible statuses are "open", "complete", and "expired".
      parameters:
        - name: session_id
          in: path
          required: true
          schema:
            type: string
            example: cs_test_12345
      responses:
        '200':
          description: Session details.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  status:
                    type: string
                    enum: [open, complete, expired]
                  amount:
                    type: integer

  /webhook/stripe:
    post:
      summary: Stripe Webhook Endpoint
      description: >
        Receives Stripe events such as checkout.session.completed.

        In development, signature verification is skipped.
        In staging and production, the signature is verified using STRIPE_WEBHOOK_SECRET.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              additionalProperties: true
      responses:
        '200':
          description: Webhook processed successfully.
