openapi: 3.0.3
info:
  title: Teachable Stripe Checkout API
  version: 1.1.0
  description: API for creating, updating, retrieving Checkout Sessions, and fetching Stripe data.

servers:
  - url: https://staging.teachable.com/api
    description: Staging (Stripe Staging API Keys)

paths:
  /checkout/session:
    post:
      summary: Create a Checkout Session
      description: |
        Creates a Stripe Checkout Session (Hosted by default).  
        You can also specify `ui_mode=embedded` for embedded testing.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                line_items:
                  type: array
                  items:
                    type: object
                    properties:
                      price:
                        type: string
                        example: price_123
                      quantity:
                        type: integer
                        example: 1
                success_url:
                  type: string
                  example: https://example.com/success
                cancel_url:
                  type: string
                  example: https://example.com/cancel
                mode:
                  type: string
                  enum: [payment, subscription]
                  default: payment
                customer_email:
                  type: string
                  example: test@example.com
                ui_mode:
                  type: string
                  enum: [hosted, embedded]
                  default: hosted
      responses:
        '201':
          description: Checkout Session created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    example: cs_test_12345
                  url:
                    type: string
                    example: https://checkout.stripe.com/pay/cs_test_12345

  /checkout/session/{session_id}:
    get:
      summary: Retrieve a Checkout Session
      description: Get a session’s details and current status.
      parameters:
        - name: session_id
          in: path
          required: true
          schema:
            type: string
            example: cs_test_12345
      responses:
        '200':
          description: Session details
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  status:
                    type: string
                    enum: [open, complete, expired]
                  amount:
                    type: integer
    patch:
      summary: Update a Checkout Session
      description: Update session with a new price, transfer data, or shipping address.
      parameters:
        - name: session_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                new_price:
                  type: string
                  example: price_456
                shipping_address:
                  type: object
                  properties:
                    line1:
                      type: string
                      example: 123 Main St
                    city:
                      type: string
                      example: New York
                    postal_code:
                      type: string
                      example: 10001
                    country:
                      type: string
                      example: US
                transfer_data:
                  type: object
                  properties:
                    destination:
                      type: string
                      example: acct_1A2B3C
                    amount:
                      type: integer
                      example: 500
      responses:
        '200':
          description: Session updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  updated:
                    type: boolean

  /payment_intents/{payment_intent_id}:
    get:
      summary: Fetch a Payment Intent
      description: Retrieve details for a specific Payment Intent.
      parameters:
        - name: payment_intent_id
          in: path
          required: true
          schema:
            type: string
            example: pi_12345
      responses:
        '200':
          description: PaymentIntent details

  /charges/{charge_id}:
    get:
      summary: Fetch a Charge
      description: Retrieve details for a specific Charge.
      parameters:
        - name: charge_id
          in: path
          required: true
          schema:
            type: string
            example: ch_12345
      responses:
        '200':
          description: Charge details

  /account:
    get:
      summary: Fetch Stripe Account
      description: Get details about the current Stripe account.
      responses:
        '200':
          description: Account details

  /webhook/stripe:
    post:
      summary: Stripe Webhook Endpoint
      description: |
        Receives events from Stripe (e.g., `checkout.session.completed`)  
        and validates the signature using `STRIPE_WEBHOOK_SECRET`.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              additionalProperties: true
      responses:
        '200':
          description: Webhook processed
